# Source : XP_Z12-012_Annexe_A_2026_V1.4_VF.xlsx from AFNOR XP-Z12-012
# with itself quotes https://service.unece.org/trade/untdid/d24a/tred/tred4451.htm
# as its source

UNTDID_4451 = {
    "AAA": "Goods item description",
    "AAB": "Payment term",
    "AAC": "Dangerous goods additional information",
    "AAD": "Dangerous goods technical name",
    "AAE": "Acknowledgement description",
    "AAF": "Rate additional information",
    "AAG": "Party instructions",
    "AAI": "General information",
    "AAJ": "Additional conditions of sale/purchase",
    "AAK": "Price conditions",
    "AAL": "Goods dimensions in characters",
    "AAM": "Equipment re-usage restrictions",
    "AAN": "Handling restriction",
    "AAO": "Error description (free text)",
    "AAP": "Response (free text)",
    "AAQ": "Package content's description",
    "AAR": "Terms of delivery",
    "AAS": "Bill of lading remarks",
    "AAT": "Mode of settlement information",
    "AAU": "Consignment invoice information",
    "AAV": "Clearance invoice information",
    "AAW": "Letter of credit information",
    "AAX": "License information",
    "AAY": "Certification statements",
    "AAZ": "Additional export information",
    "ABA": "Tariff statements",
    "ABB": "Medical history",
    "ABC": "Conditions of sale or purchase",
    "ABD": "Contract document type",
    "ABE": "Additional terms and/or conditions (documentary credit)",
    "ABF": "Instructions or information about standby documentary",
    "ABG": "Instructions or information about partial shipment(s)",
    "ABH": "Instructions or information about transhipment(s)",
    "ABI": "Additional handling instructions documentary credit",
    "ABJ": "Domestic routing information",
    "ABK": "Chargeable category of equipment",
    "ABL": "Government information",
    "ABM": "Onward routing information",
    "ABN": "Accounting information",
    "ABO": "Discrepancy information",
    "ABP": "Confirmation instructions",
    "ABQ": "Method of issuance",
    "ABR": "Documents delivery instructions",
    "ABS": "Additional conditions",
    "ABT": "Information/instructions about additional amounts covered",
    "ABU": "Deferred payment termed additional",
    "ABV": "Acceptance terms additional",
    "ABW": "Negotiation terms additional",
    "ABX": "Document name and documentary requirements",
    "ABZ": "Instructions/information about revolving documentary credit",
    "ACA": "Documentary requirements",
    "ACB": "Additional information",
    "ACC": "Factor assignment clause",
    "ACD": "Reason",
    "ACE": "Dispute",
    "ACF": "Additional attribute information",
    "ACG": "Absence declaration",
    "ACH": "Aggregation statement",
    "ACI": "Compilation statement",
    "ACJ": "Definitional exception",
    "ACK": "Privacy statement",
    "ACL": "Quality statement",
    "ACM": "Statistical description",
    "ACN": "Statistical definition",
    "ACO": "Statistical name",
    "ACP": "Statistical title",
    "ACQ": "Off-dimension information",
    "ACR": "Unexpected stops information",
    "ACS": "Principles",
    "ACT": "Terms and definition",
    "ACU": "Segment name",
    "ACV": "Simple data element name",
    "ACW": "Scope",
    "ACX": "Message type name",
    "ACY": "Introduction",
    "ACZ": "Glossary",
    "ADA": "Functional definition",
    "ADB": "Examples",
    "ADC": "Cover page",
    "ADD": "Dependency (syntax) notes",
    "ADE": "Code value name",
    "ADF": "Code list name",
    "ADG": "Clarification of usage",
    "ADH": "Composite data element name",
    "ADI": "Field of application",
    "ADJ": "Type of assets and liabilities",
    "ADK": "Promotion information",
    "ADL": "Meter condition",
    "ADM": "Meter reading information",
    "ADN": "Type of transaction reason",
    "ADO": "Type of survey question",
    "ADP": "Carrier's agent counter information",
    "ADQ": "Description of work item on equipment",
    "ADR": "Message definition",
    "ADS": "Booked item information",
    "ADT": "Source of document",
    "ADU": "Note",
    "ADV": "Fixed part of segment clarification text",
    "ADW": "Characteristics of goods",
    "ADX": "Additional discharge instructions",
    "ADY": "Container stripping instructions",
    "ADZ": "CSC (Container Safety Convention) plate information",
    "AEA": "Cargo remarks",
    "AEB": "Temperature control instructions",
    "AEC": "Text refers to expected data",
    "AED": "Text refers to received data",
    "AEE": "Section clarification text",
    "AEF": "Information to the beneficiary",
    "AEG": "Information to the applicant",
    "AEH": "Instructions to the beneficiary",
    "AEI": "Instructions to the applicant",
    "AEJ": "Controlled atmosphere",
    "AEK": "Take off annotation",
    "AEL": "Price variation narrative",
    "AEM": "Documentary credit amendment instructions",
    "AEN": "Standard method narrative",
    "AEO": "Project narrative",
    "AEP": "Radioactive goods, additional information",
    "AEQ": "Bank-to-bank information",
    "AER": "Reimbursement instructions",
    "AES": "Reason for amending a message",
    "AET": "Instructions to the paying and/or accepting and/or",
    "AEU": "Interest instructions",
    "AEV": "Agent commission",
    "AEW": "Remitting bank instructions",
    "AEX": "Instructions to the collecting bank",
    "AEY": "Collection amount instructions",
    "AEZ": "Internal auditing information",
    "AFA": "Constraint",
    "AFB": "Comment",
    "AFC": "Semantic note",
    "AFD": "Help text",
    "AFE": "Legend",
    "AFF": "Batch code structure",
    "AFG": "Product application",
    "AFH": "Customer complaint",
    "AFI": "Probable cause of fault",
    "AFJ": "Defect description",
    "AFK": "Repair description",
    "AFL": "Review comments",
    "AFM": "Title",
    "AFN": "Description of amount",
    "AFO": "Responsibilities",
    "AFP": "Supplier",
    "AFQ": "Purchase region",
    "AFR": "Affiliation",
    "AFS": "Borrower",
    "AFT": "Line of business",
    "AFU": "Financial institution",
    "AFV": "Business founder",
    "AFW": "Business history",
    "AFX": "Banking arrangements",
    "AFY": "Business origin",
    "AFZ": "Brand names' description",
    "AGA": "Business financing details",
    "AGB": "Competition",
    "AGC": "Construction process details",
    "AGD": "Construction specialty",
    "AGE": "Contract information",
    "AGF": "Corporate filing",
    "AGG": "Customer information",
    "AGH": "Copyright notice",
    "AGI": "Contingent debt",
    "AGJ": "Conviction details",
    "AGK": "Equipment",
    "AGL": "Workforce description",
    "AGM": "Exemption",
    "AGN": "Future plans",
    "AGO": "Interviewee conversation information",
    "AGP": "Intangible asset",
    "AGQ": "Inventory",
    "AGR": "Investment",
    "AGS": "Intercompany relations information",
    "AGT": "Joint venture",
    "AGU": "Loan",
    "AGV": "Long term debt",
    "AGW": "Location",
    "AGX": "Current legal structure",
    "AGY": "Marital contract",
    "AGZ": "Marketing activities",
    "AHA": "Merger",
    "AHB": "Marketable securities",
    "AHC": "Business debt",
    "AHD": "Original legal structure",
    "AHE": "Employee sharing arrangements",
    "AHF": "Organization details",
    "AHG": "Public record details",
    "AHH": "Price range",
    "AHI": "Qualifications",
    "AHJ": "Registered activity",
    "AHK": "Criminal sentence",
    "AHL": "Sales method",
    "AHM": "Educational institution information",
    "AHN": "Status details",
    "AHO": "Sales",
    "AHP": "Spouse information",
    "AHQ": "Educational degree information",
    "AHR": "Shareholding information",
    "AHS": "Sales territory",
    "AHT": "Accountant's comments",
    "AHU": "Exemption law location",
    "AHV": "Share classifications",
    "AHW": "Forecast",
    "AHX": "Event location",
    "AHY": "Facility occupancy",
    "AHZ": "Import and export details",
    "AIA": "Additional facility information",
    "AIB": "Inventory value",
    "AIC": "Education",
    "AID": "Event",
    "AIE": "Agent",
    "AIF": "Domestically agreed financial statement details",
    "AIG": "Other current asset description",
    "AIH": "Other current liability description",
    "AII": "Former business activity",
    "AIJ": "Trade name use",
    "AIK": "Signing authority",
    "AIL": "Guarantee",
    "AIM": "Holding company operation",
    "AIN": "Consignment routing",
    "AIO": "Letter of protest",
    "AIP": "Question",
    "AIQ": "Party information",
    "AIR": "Area boundaries description",
    "AIS": "Advertisement information",
    "AIT": "Financial statement details",
    "AIU": "Access instructions",
    "AIV": "Liquidity",
    "AIW": "Credit line",
    "AIX": "Warranty terms",
    "AIY": "Division description",
    "AIZ": "Reporting instruction",
    "AJA": "Examination result",
    "AJB": "Laboratory result",
    "ALC": "Allowance/charge information",
    "ALD": "X-ray result",
    "ALE": "Pathology result",
    "ALF": "Intervention description",
    "ALG": "Summary of admittance",
    "ALH": "Medical treatment course detail",
    "ALI": "Prognosis",
    "ALJ": "Instruction to patient",
    "ALK": "Instruction to physician",
    "ALL": "All documents",
    "ALM": "Medicine treatment",
    "ALN": "Medicine dosage and administration",
    "ALO": "Availability of patient",
    "ALP": "Reason for service request",
    "ALQ": "Purpose of service",
    "ARR": "Arrival conditions",
    "ARS": "Service requester's comment",
    "AUT": "Authentication",
    "AUU": "Requested location description",
    "AUV": "Medicine administration condition",
    "AUW": "Patient information",
    "AUX": "Precautionary measure",
    "AUY": "Service characteristic",
    "AUZ": "Planned event comment",
    "AVA": "Expected delay comment",
    "AVB": "Transport requirements comment",
    "AVC": "Temporary approval condition",
    "AVD": "Customs Valuation Information",
    "AVE": "Value Added Tax (VAT) margin scheme",
    "AVF": "Maritime Declaration of Health",
    "BAG": "Passenger baggage information",
    "BAH": "Maritime Declaration of Health",
    "BAI": "Additional product information address",
    "BAJ": "Information to be printed on despatch advice",
    "BAK": "Missing goods remarks",
    "BAL": "Non-acceptance information",
    "BAM": "Returns information",
    "BAN": "Sub-line item information",
    "BAO": "Test information",
    "BAP": "External link",
    "BAQ": "VAT exemption reason",
    "BAR": "Processing Instructions",
    "BAS": "Relay Instructions",
    "BAT": "SIMA applicable",
    "BAU": "Appeals program code",
    "BAV": "SIMA subject",
    "BAW": "Surtax applicable",
    "BAX": "SIMA security bond",
    "BAY": "Surtax subject",
    "BAZ": "Safeguard applicable",
    "BBA": "Safeguard applicable",
    "BBB": "Safeguard subject",
    "BLC": "Transport contract document clause",
    "BLD": "Instruction to prepare the patient",
    "BLE": "Medicine treatment comment",
    "BLF": "Examination result comment",
    "BLG": "Service request comment",
    "BLH": "Prescription reason",
    "BLI": "Prescription comment",
    "BLJ": "Clinical investigation comment",
    "BLK": "Medicinal specification comment",
    "BLL": "Economic contribution comment",
    "BLM": "Status of a plan",
    "BLN": "Random sample test information",
    "BLO": "Period of time",
    "BLP": "Legislation",
    "BLQ": "Security measures requested",
    "BLR": "Transport contract document remark",
    "BLS": "Previous port of call security information",
    "BLT": "Security information",
    "BLU": "Waste information",
    "BLV": "B2C marketing information, short description",
    "BLW": "B2B marketing information, long description",
    "BLX": "B2C marketing information, long description",
    "BLY": "Product ingredients",
    "BLZ": "Location short name",
    "BMA": "Packaging material information",
    "BMB": "Filler material information",
    "BMC": "Ship-to-ship activity information",
    "BMD": "Package material description",
    "BME": "Consumer level package marking",
    "BMF": "SIMA measure in force",
    "BMG": "Pre-CARM",
    "BMH": "SIMA measure type",
    "CCI": "Customs clearance instructions",
    "CCJ": "Sub Type Code",
    "CCK": "SIMA information",
    "CCL": "Time limit end",
    "CCM": "Time limit start",
    "CCN": "Warehouse time limit",
    "CCO": "Value for duty information",
    "CEX": "Customs clearance instructions export",
    "CHG": "Change information",
    "CIP": "Customs clearance instruction import",
    "CLP": "Clearance place requested",
    "CLR": "Loading remarks",
    "COI": "Order information",
    "CUR": "Customer remarks",
    "CUS": "Customs declaration information",
    "DAR": "Damage remarks",
    "DCL": "Document issuer declaration",
    "DEL": "Delivery information",
    "DIN": "Delivery instructions",
    "DOC": "Documentation instructions",
    "DUT": "Duty declaration",
    "EUR": "Effective used routing",
    "FBC": "First block to be printed on the transport contract",
    "GBL": "Government bill of lading information",
    "GEN": "Entire transaction set",
    "GS7": "Further information concerning GGVS par. 7",
    "HAN": "Consignment handling instruction",
    "HAZ": "Hazard information",
    "ICN": "Consignment information for consignee",
    "IIN": "Insurance instructions",
    "IMI": "Invoice mailing instructions",
    "IND": "Commercial invoice item description",
    "INS": "Insurance information",
    "INV": "Invoice instruction",
    "IRP": "Information for railway purpose",
    "ITR": "Inland transport details",
    "ITS": "Testing instructions",
    "LAN": "Location Alias",
    "LIN": "Line item",
    "LOI": "Loading instruction",
    "MCO": "Miscellaneous charge order",
    "MDH": "Maritime Declaration of Health",
    "MKS": "Additional marks/numbers information",
    "ORI": "Order instruction",
    "OSI": "Other service information",
    "PAC": "Packing/marking information",
    "PAI": "Payment instructions information",
    "PAY": "Payables information",
    "PKG": "Packaging information",
    "PKT": "Packaging terms information",
    "PMD": "Payment detail/remittance information",
    "PMT": "Payment information",
    "PRD": "Product information",
    "PRF": "Price calculation formula",
    "PRI": "Priority information",
    "PUR": "Purchasing information",
    "QIN": "Quarantine instructions",
    "QQD": "Quality demands/requirements",
    "QUT": "Quotation instruction/information",
    "RAH": "Risk and handling information",
    "REG": "Regulatory information",
    "RET": "Return to origin information",
    "REV": "Receivables",
    "RQR": "Consignment route",
    "SAF": "Safety information",
    "SIC": "Consignment documentary instruction",
    "SIN": "Special instructions",
    "SLR": "Ship line requested",
    "SPA": "Special permission for transport, generally",
    "SPG": "Special permission concerning the goods to be transported",
    "SPH": "Special handling",
    "SPP": "Special permission concerning package",
    "SPT": "Special permission concerning transport means",
    "SRN": "Subsidiary risk number (IATA/DGR)",
    "SSR": "Special service request",
    "SUR": "Supplier remarks",
    "TCA": "Consignment tariff",
    "TDT": "Consignment transport",
    "TRA": "Transportation information",
    "TRR": "Requested tariff",
    "TXD": "Tax declaration",
    "WHI": "Warehouse instruction/information",
    "ZZZ": "Mutually defined",
}


UNTDID_5189 = {
    "1": "Handling commission",
    "2": "Amendment commission",
    "3": "Acceptance commission",
    "4": "Commission for obtaining acceptance",
    "5": "Commission on delivery",
    "6": "Advising commission",
    "7": "Confirmation commission",
    "8": "Deferred payment commission",
    "9": "Commission for taking up documents",
    "10": "Opening commission",
    "11": "Fee for payment under reserve",
    "12": "Discrepancy fee",
    "13": "Domicilation commission",
    "14": "Commission for release of goods",
    "15": "Collection commission",
    "16": "Negotiation commission",
    "17": "Return commission",
    "18": "B/L splitting charges",
    "19": "Trust commission",
    "20": "Transfer commission",
    "21": "Commission for opening irrevocable documentary credits",
    "22": "Pre-advice commission",
    "23": "Supervisory commission",
    "24": "Model charges",
    "25": "Risk commission",
    "26": "Guarantee commission",
    "27": "Reimbursement commission",
    "28": "Stamp duty",
    "29": "Brokerage",
    "30": "Bank charges",
    "31": "Bank charges information",
    "32": "Courier fee",
    "33": "Phone fee",
    "34": "Postage fee",
    "35": "S.W.I.F.T. fee",
    "36": "Telex fee",
    "37": "Penalty for late delivery of documents",
    "38": "Penalty for late delivery of valuation of works",
    "39": "Penalty for execution of works behind schedule",
    "40": "Other penalties",
    "41": "Bonus for works ahead of schedule",
    "42": "Other bonus",
    "44": "Project management cost",
    "45": "Pro rata retention",
    "46": "Contractual retention",
    "47": "Other retentions",
    "48": "Interest on arrears",
    "49": "Interest",
    "50": "Charge per credit cover",
    "51": "Charge per unused credit cover",
    "52": "Minimum commission",
    "53": "Factoring commission",
    "54": "Chamber of commerce charge",
    "55": "Transfer charges",
    "56": "Repatriation charges",
    "57": "Miscellaneous charges",
    "58": "Foreign exchange charges",
    "59": "Agreed debit interest charge",
    "60": "Manufacturer's consumer discount",
    "61": "Fax advice charge",
    "62": "Due to military status",
    "63": "Due to work accident",
    "64": "Special agreement",
    "65": "Production error discount",
    "66": "New outlet discount",
    "67": "Sample discount",
    "68": "End-of-range discount",
    "69": "Charge for a customer specific finish",
    "70": "Incoterm discount",
    "71": "Point of sales threshold allowance",
    "72": "Technical modification costs",
    "73": "Job-order production costs",
    "74": "Off-premises costs",
    "75": "Additional processing costs",
    "76": "Attesting charge",
    "77": "Rush delivery surcharge",
    "78": "Special construction costs",
    "79": "Freight charges",
    "80": "Packing charge",
    "81": "Repair charge",
    "82": "Loading charge",
    "83": "Setup charge",
    "84": "Testing charge",
    "85": "Warehousing charge",
    "86": "Gold surcharge",
    "87": "Copper surcharge",
    "88": "Material surcharge/deduction",
    "89": "Lead surcharge",
    "90": "Price index surcharge",
    "91": "Platinum surcharge",
    "92": "Silver surcharge",
    "93": "Wolfram surcharge",
    "94": "Aluminum surcharge",
    "95": "Discount",
    "96": "Insurance",
    "97": "Minimum order / minimum billing charge",
    "98": "Material surcharge (special materials)",
    "99": "Surcharge",
    "100": "Special rebate",
    "101": "Carbon footprint charge",
    "102": "Fixed long term",
    "103": "Temporary",
    "104": "Standard",
    "105": "Yearly turnover",
    "106": "Withheld taxes and social security contributions",
}

UNTDID_7161 = {
    "AA": "Advertising",
    "AAA": "Telecommunication",
    "AAC": "Technical modification",
    "AAD": "Job-order production",
    "AAE": "Outlays",
    "AAF": "Off-premises",
    "AAH": "Additional processing",
    "AAI": "Attesting",
    "AAS": "Acceptance",
    "AAT": "Rush delivery",
    "AAV": "Special construction",
    "AAY": "Airport facilities",
    "AAZ": "Concession",
    "ABA": "Compulsory storage",
    "ABB": "Fuel removal",
    "ABC": "Into plane",
    "ABD": "Overtime",
    "ABF": "Tooling",
    "ABK": "Miscellaneous",
    "ABL": "Additional packaging",
    "ABN": "Dunnage",
    "ABR": "Containerisation",
    "ABS": "Carton packing",
    "ABT": "Hessian wrapped",
    "ABU": "Polyethylene wrap packing",
    "ACF": "Miscellaneous treatment",
    "ACG": "Enamelling treatment",
    "ACH": "Heat treatment",
    "ACI": "Plating treatment",
    "ACJ": "Painting",
    "ACK": "Polishing",
    "ACL": "Priming",
    "ACM": "Preservation treatment",
    "ACS": "Fitting",
    "ADC": "Consolidation",
    "ADE": "Bill of lading",
    "ADJ": "Airbag",
    "ADK": "Transfer",
    "ADL": "Slipsheet",
    "ADM": "Binding",
    "ADN": "Repair or replacement of broken returnable package",
    "ADO": "Efficient logistics",
    "ADP": "Merchandising",
    "ADQ": "Product mix",
    "ADR": "Other services",
    "ADT": "Pick-up",
    "ADW": "Chronic illness",
    "ADY": "New product introduction",
    "ADZ": "Direct delivery",
    "AEA": "Diversion",
    "AEB": "Disconnect",
    "AEC": "Distribution",
    "AED": "Handling of hazardous cargo",
    "AEF": "Rents and leases",
    "AEH": "Location differential",
    "AEI": "Aircraft refueling",
    "AEJ": "Fuel shipped into storage",
    "AEK": "Cash on delivery",
    "AEL": "Small order processing service",
    "AEM": "Clerical or administrative services",
    "AEN": "Guarantee",
    "AEO": "Collection and recycling",
    "AEP": "Copyright fee collection",
    "AES": "Veterinary inspection service",
    "AET": "Pensioner service",
    "AEU": "Medicine free pass holder",
    "AEV": "Environmental protection service",
    "AEW": "Environmental clean-up service",
    "AEX": "National cheque processing service outside account area",
    "AEY": "National payment service outside account area",
    "AEZ": "National payment service within account area",
    "AJ": "Adjustments",
    "AU": "Authentication",
    "CA": "Cataloguing",
    "CAB": "Cartage",
    "CAD": "Certification",
    "CAE": "Certificate of conformance",
    "CAF": "Certificate of origin",
    "CAI": "Cutting",
    "CAJ": "Consular service",
    "CAK": "Customer collection",
    "CAL": "Payroll payment service",
    "CAM": "Cash transportation",
    "CAN": "Home banking service",
    "CAO": "Bilateral agreement service",
    "CAP": "Insurance brokerage service",
    "CAQ": "Cheque generation",
    "CAR": "Preferential merchandising location",
    "CAS": "Crane",
    "CAT": "Special colour service",
    "CAU": "Sorting",
    "CAV": "Battery collection and recycling",
    "CAW": "Product take back fee",
    "CAX": "Quality control released",
    "CAY": "Quality control held",
    "CAZ": "Quality control embargo",
    "CD": "Car loading",
    "CG": "Cleaning",
    "CS": "Cigarette stamping",
    "CT": "Count and recount",
    "DAB": "Layout/design",
    "DAC": "Assortment allowance",
    "DAD": "Driver assigned unloading",
    "DAF": "Debtor bound",
    "DAG": "Dealer allowance",
    "DAH": "Allowance transferable to the consumer",
    "DAI": "Growth of business",
    "DAJ": "Introduction allowance",
    "DAK": "Multi-buy promotion",
    "DAL": "Partnership",
    "DAM": "Return handling",
    "DAN": "Minimum order not fulfilled charge",
    "DAO": "Point of sales threshold allowance",
    "DAP": "Wholesaling discount",
    "DAQ": "Documentary credits transfer commission",
    "DL": "Delivery",
    "EG": "Engraving",
    "EP": "Expediting",
    "ER": "Exchange rate guarantee",
    "FAA": "Fabrication",
    "FAB": "Freight equalization",
    "FAC": "Freight extraordinary handling",
    "FC": "Freight service",
    "FH": "Filling/handling",
    "FI": "Financing",
    "GAA": "Grinding",
    "HAA": "Hose",
    "HD": "Handling",
    "HH": "Hoisting and hauling",
    "IAA": "Installation",
    "IAB": "Installation and warranty",
    "ID": "Inside delivery",
    "IF": "Inspection",
    "IR": "Installation and training",
    "IS": "Invoicing",
    "KO": "Koshering",
    "L1": "Carrier count",
    "LA": "Labelling",
    "LAA": "Labour",
    "LAB": "Repair and return",
    "LF": "Legalisation",
    "MAE": "Mounting",
    "MI": "Mail invoice",
    "ML": "Mail invoice to each location",
    "NAA": "Non-returnable containers",
    "OA": "Outside cable connectors",
    "PA": "Invoice with shipment",
    "PAA": "Phosphatizing (steel treatment)",
    "PC": "Packing",
    "PL": "Palletizing",
    "RAB": "Repacking",
    "RAC": "Repair",
    "RAD": "Returnable container",
    "RAF": "Restocking",
    "RE": "Re-delivery",
    "RF": "Refurbishing",
    "RH": "Rail wagon hire",
    "RV": "Loading",
    "SA": "Salvaging",
    "SAA": "Shipping and handling",
    "SAD": "Special packaging",
    "SAE": "Stamping",
    "SAI": "Consignee unload",
    "SG": "Shrink-wrap",
    "SH": "Special handling",
    "SM": "Special finish",
    "SU": "Set-up",
    "TAB": "Tank renting",
    "TAC": "Testing",
    "TT": "Transportation - third party billing",
    "TV": "Transportation by vendor",
    "V1": "Drop yard",
    "V2": "Drop dock",
    "WH": "Warehousing",
    "XAA": "Combine all same day shipment",
    "YY": "Split pick-up",
    "ZZZ": "Mutually defined",
}


def untdid_get_label(untdid_table, code):
    untdid_table2dict = {
        "4451": UNTDID_4451,
        "5189": UNTDID_5189,
        "7161": UNTDID_7161,
    }
    if untdid_table not in untdid_table2dict:
        raise ValueError(
            "Wrong value for untdid arg. "
            f"Possible values: {', '.join(untdid_table2dict.keys())}"
        )
    if not code:
        return None
    untdid_dict = untdid_table2dict[untdid_table]
    if not isinstance(code, (str, int)):
        raise ValueError("Argument code must be a string or integer")
    if isinstance(code, int):
        code = str(code)
    else:
        code = code.strip().upper()
    return untdid_dict.get(code)
